.\" gde2-system-log.1 - GDE2 logfile viewer
.\" Copyright 2001  Jochen Voss
.TH gde2-system-log 1 "Aug 09 2002" "gde2-utils 2.0.0"
.SH NAME
gde2-system-log \- the GDE2 System Log Viewer
.SH SYNOPSIS
.B gde2-system-log
.sp
or select
.B System Log
from the
.B System Tools
submenu of the Applications menu.
.SH DESCRIPTION
.B GDE2 System Log Viewer
is a simple utility to display system log files.
.SH AUTHOR
The
.B GDE2 System Log Viewer
was written by Cesar Miquel <miquel@df.uba.ar>.
.PP
This manual page was written by Jochen Voss
<voss@mathematik.uni-kl.de>.
.SH FILES
.TP
.I /var/log/messages
The system's main logfile.
.TP
.I /etc/syslog.conf
Configuration file for syslogd.  See
.BR syslog.conf (5)
for exact information.
.SH SEE ALSO
.BR syslogd (8),
.BR sysklogd (8),
.BR syslog.conf (5),
.BR syslogd-listfiles (8)
